// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://getjbnslnwglazujjgxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdldGpibnNsbndnbGF6dWpqZ3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDgzMDksImV4cCI6MjA1OTk4NDMwOX0.sZAM9cgl-GC-DlVrM0bLhp51x4co1aOy1JSGhYxyghY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);